name: E2E - Manual Execution

on:
  workflow_dispatch:
      inputs:
          tag:
            description: 'Test scenario tags'
            required: true
            options:
              - SMOKE
              - AUREUM
              - REGRESSION
              - API
          target_environment:
            description: 'Environment the tests will hit'
            required: true
            options:
              - dev

jobs:
  run-automated-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        id: checkout-repo
        uses: actions/checkout@v3

  trigger-e2e-tests-actions:
    uses: ./.github/workflows/e2e_run.yaml
    with:
      tag: ${{ inputs.tag }}
      target_environment: ${{ inputs.target_environment }}
